# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Irish Debbarma
tagline:          'My personal website'
description:      'For the night is dark and full of terrors'
url:              https://debbarma2000.github.io/test_portfolio
baseurl:          /

author:
  name:           'Irish Debbarma'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Debbarma2000/test_portfolio
